[font]
size = 12.0

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "Regular"

[font.bold]
family = "JetBrainsMonoNerdFont"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNerdFont"
style = "Italic"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0
