theme = "catppuccin_frappe"

[editor]
rulers = [100]
cursorline = true

[keys.insert]
k = { j = "normal_mode" } # Maps `jk` to exit insert mode

[keys.normal]
"," = { q = ":quit", w = ":write" }
"space" = { space = "file_picker_in_current_directory", "," = "buffer_picker" }
"ret" = "goto_word"
